name: 'Setup pnpm'
description: 'Setup pnpm with caching'
author: 'Klever Labs'

inputs:
  version:
    description: 'Version of pnpm to install'
    required: false
    default: '8'
  working-directory:
    description: 'Working directory containing pnpm-lock.yaml'
    required: false
    default: '.'
  run-install:
    description: 'Whether to run pnpm install'
    required: false
    default: 'true'
  install-args:
    description: 'Additional arguments for pnpm install'
    required: false
    default: '--frozen-lockfile'

outputs:
  store-path:
    description: 'The pnpm store path'
    value: ${{ steps.pnpm-store.outputs.path }}
  cache-hit:
    description: 'Whether the cache was hit'
    value: ${{ steps.cache-pnpm.outputs.cache-hit }}

runs:
  using: 'composite'
  steps:
    - name: Install pnpm
      uses: pnpm/action-setup@v2
      with:
        version: ${{ inputs.version }}
        
    - name: Get pnpm store directory
      id: pnpm-store
      shell: bash
      run: |
        STORE_PATH=$(pnpm store path --silent)
        echo "path=$STORE_PATH" >> $GITHUB_OUTPUT
        echo "STORE_PATH=$STORE_PATH" >> $GITHUB_ENV
        
    - name: Setup pnpm cache
      id: cache-pnpm
      uses: actions/cache@v3
      with:
        path: ${{ steps.pnpm-store.outputs.path }}
        key: ${{ runner.os }}-pnpm-store-${{ hashFiles(format('{0}/pnpm-lock.yaml', inputs.working-directory)) }}
        restore-keys: |
          ${{ runner.os }}-pnpm-store-
          
    - name: Install dependencies
      if: inputs.run-install == 'true'
      shell: bash
      working-directory: ${{ inputs.working-directory }}
      run: pnpm install ${{ inputs.install-args }}

branding:
  icon: 'package'
  color: 'orange'